model (
    name warehouse.calendar.calendar,
    kind full,
    grain (date_nk),
    columns (
        date_nk date,
        date_id integer,
        ordinal_date integer,
        year_quarter integer,
        year_month integer,
        year_week integer,
        year_number integer,
        quarter_number integer,
        month_number integer,
        week_number integer,
        day_of_year_number integer,
        day_of_month_number integer,
        day_of_week_number integer,
        day_name varchar,
        day_name_abbr varchar,
        month_name varchar,
        month_name_abbr varchar,
        is_month_start boolean,
        is_month_end boolean,
        is_quarter_start boolean,
        is_quarter_end boolean,
        is_year_start boolean,
        is_year_end boolean,
        is_leap_year boolean,
        is_day_weekday boolean,
    ),
);


select
    date_nk,
    date_id,
    ordinal_date,
    year_quarter,
    year_month,
    year_week,
    year_number,
    quarter_number,
    month_number,
    week_number,
    day_of_year_number,
    day_of_month_number,
    day_of_week_number,
    day_name,
    day_name_abbr,
    month_name,
    month_name_abbr,
    is_month_start,
    is_month_end,
    is_quarter_start,
    is_quarter_end,
    is_year_start,
    is_year_end,
    is_leap_year,
    is_day_weekday,
from 'https://raw.githubusercontent.com/billwallis/dbt-calendar/refs/tags/v0.0.1/seeds/calendar.csv'
;
