# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
---
networks:
  shaper:
    name: shaper

services:
  shaper:
    image: taleshape/shaper:0.21.0
    container_name: Shaper
    volumes:
      # Shaper internal state
      - type: bind
        source: ./shaper
        target: /data
    ports: ["5454:5454"]  # http://localhost:5454/
    networks: ["shaper"]
    environment:
      MOTHERDUCK_TOKEN: $MOTHERDUCK_TOKEN
