# yaml-language-server: $schema=https://json.schemastore.org/pyproject.json
[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "billiam-data-stack"
version = "0.0.0"
description = "Analytical data stack for life admin."
authors = [{name = "billwallis"}]
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.13"
dependencies = [
    "dlt[motherduck]>=1.28.1",
    "duckdb>=1.5.0,<=1.5.3",  # capped by MotherDuck
    "google-api-python-client>=2.190.0",
    "google-auth-httplib2>=0.3.0",
    "google-auth-oauthlib>=1.3.0",
    "sqlmesh[github]>=0.232.0",
]
scripts.ingest = "ingestion.__main__:main"

[dependency-groups]
dev = [
    "poethepoet>=0.46.0",
    "pre-commit>=4.6.0",
    "shaper-bin==0.21.0",
]
# for building own OAuth2 server
oauth2 = [
    "flask>=3.1.3",
]


[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
namespace = true


[tool.poe]
verbosity = -1
envfile.optional = ".env"

[tool.poe.tasks]
install.shell = """
    uv sync --refresh
    uv run pre-commit install --install-hooks
"""
upgrade.shell = """
    uv sync --refresh --upgrade
    uv run pre-commit autoupdate
"""
docker-up = "docker-compose --file docker-compose.yaml --project-name billiam-data-stack up --detach"
docker-down = "docker-compose --file docker-compose.yaml --project-name billiam-data-stack down --remove-orphans"
auth.shell = """
    python -m tools.oura_oauth
"""

# SQLMesh wrappers (`cmd` rather than `shell` for colour output)
run = [
    {cmd = "docker desktop start"},
    "docker-up",
    {cmd = "uv run -m src.ingestion"},
    {cmd = "sqlmesh -p src/transformation run dev  --ignore-cron"},
    {cmd = "sqlmesh -p src/transformation run prod --ignore-cron"},
    "deploy-bi",
]
clean = [
    {cmd = "sqlmesh -p src/transformation clean"},
    {cmd = "sqlmesh -p src/transformation janitor"},
]
debug = [
    {cmd = "sqlmesh -p src/transformation info"},
    {cmd = "sqlmesh -p src/transformation check_intervals"},
]

render = "sqlmesh -p src/transformation render"
test = "sqlmesh -p src/transformation test -vv"

migrate = "sqlmesh -p src/transformation migrate"
plan = "sqlmesh -p src/transformation plan"
audit = "sqlmesh -p src/transformation audit"

sqlmesh = "sqlmesh -p src/transformation"

[tool.poe.tasks.lint]
control.expr = "sys.platform"

[[tool.poe.tasks.lint.switch]]
case = "win32"
shell = """
    echo '=== pre-commit checks ==='
    SKIP=identity uv run pre-commit run --all-files --hook-stage pre-commit
    echo '=== pre-push checks ==='
    SKIP=identity uv run pre-commit run --all-files --hook-stage pre-push
    echo '=== sqlmesh checks ==='
    sqlmesh -p src/transformation lint
"""

[[tool.poe.tasks.lint.switch]]
shell = """
    echo '\\033[0;34mpre-commit checks\\033[0m'
    SKIP=identity uv run pre-commit run --all-files --hook-stage pre-commit
    echo '\\033[0;34mpre-push checks\\033[0m'
    SKIP=identity uv run pre-commit run --all-files --hook-stage pre-push
    echo '\\033[0;34msqlmesh checks\\033[0m'
    sqlmesh -p src/transformation lint
"""

[tool.poe.tasks.deploy-bi]
control.expr = "sys.platform"

[[tool.poe.tasks.deploy-bi.switch]]
case = "win32"
sequence = [
    {cmd = "docker run --rm --mount type=bind,source=./tmp/shaper.json,target=/shaper.json --volume ./src/reporting:/src/reporting --network shaper taleshape/shaper:0.21.0 shaper ids"},
    {cmd = "docker run --rm --mount type=bind,source=./tmp/shaper.json,target=/shaper.json --volume ./src/reporting:/src/reporting --network shaper taleshape/shaper:0.21.0 shaper deploy"},
    {cmd = "python -c 'import time; time.sleep(1)'"},
    {cmd = """python -c 'import webbrowser; webbrowser.open("http://localhost:5454")'"""},
]

[[tool.poe.tasks.deploy-bi.switch]]
shell = """
    shaper ids
    shaper deploy
    sleep 1
    open 'http://localhost:5454'
"""


[tool.ruff]
line-length = 80
indent-width = 4
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
    "ANN",   # flake8-annotations
    "B",     # flake8-bugbear
    "E",     # pycodestyle-error
    "F",     # Pyflakes
    "FURB",  # refurb
    "I",     # isort
    "N",     # pep8-naming
    "PL",    # Pylint
    "PERF",  # Perflint
    "RUF",   # Ruff-specific
    "S",     # flake8-bandit
    "UP",    # pyupgrade
    "W",     # pycodestyle-warning
]
ignore = [
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed
    "E501",    # Line too long
]
fixable = ["ALL"]
unfixable = []
# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# https://github.com/astral-sh/ruff/issues/4368
[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "ANN001",   # Missing type annotation for function argument
    "ANN201",   # Missing return type annotation for public function
    "S101",     # Use of `assert` detected
    "PLR2004",  # Magic value used in comparison
    "PLR0913",  # Too many arguments in function definition
]
