query($user: String!) {
    user(login: $user) {
        # anyPinnableItems(type: ...)
        # avatarUrl(size: ...)
        bio
        bioHTML
        # canReceiveOrganizationEmailsWhenNotificationsRestricted(login: ...)
        commitComments {totalCount}
        company
        companyHTML
        # contributionsCollection(organisationId: ..., from: ..., to: ...)
        # copilotEndpoints {api originTracker proxy telemetry}
        createdAt
        databaseId
        email
        enterprises {totalCount}
        estimatedNextSponsorsPayoutInCents
        followers {totalCount}
        following {totalCount}
        # gist(name: ...) {}
        gistComments {totalCount}
        gists {totalCount}
        hasSponsorsListing
        # hovercard(primarySubjectId: ...) {}
        id
        interactionAbility {expiresAt limit origin}
        isBountyHunter
        isCampusExpert
        isDeveloperProgramMember
        isEmployee
        # isFollowingViewer
        isGitHubStar
        isHireable
        isSiteAdmin
        # isSponsoredBy(accountLogin: ...)
        # isSponsoringViewer
        # isViewer
        issueComments {totalCount}
        issues {totalCount}
        itemShowcase {
            hasPinnedItems
            items {totalCount}
        }
        lifetimeReceivedSponsorshipValues {totalCount}
        lists {totalCount}
        location
        login
        monthlyEstimatedSponsorsIncomeInCents
        name
        # organization(login: ...) {}
        # organizationVerifiedDomainEmails(login: ...)
        organizations {totalCount}
        packages {totalCount}
        pinnableItems {totalCount}
        pinnedItems {totalCount}
        pinnedItemsRemaining
        # project(number: ...)  # DEPRECATED
        # projectV2(number: ...)
        # projects(...) {totalCount pageInfo {} edges {} nodes {}}  # DEPRECATED
        projectsResourcePath
        projectsUrl
        projectsV2 {totalCount}
        pronouns
        publicKeys {totalCount}
        pullRequests {totalCount}
        recentProjects {totalCount}
        repositories {totalCount}
        repositoriesContributedTo {totalCount}
        # repository(name: ..., followRenames: true) {}
        repositoryDiscussionComments {totalCount}
        repositoryDiscussions {totalCount}
        resourcePath
        savedReplies {totalCount}
        socialAccounts {totalCount}
        sponsoring {totalCount}
        sponsors {totalCount}
        sponsorsActivities {totalCount}
        # sponsorsListing {}
        # sponsorshipForViewerAsSponsor(activeOnly: true) {}
        # sponsorshipForViewerAsSponsorable(activeOnly: true) {}
        sponsorshipNewsletters {totalCount}
        sponsorshipsAsMaintainer {totalCount}
        sponsorshipsAsSponsor {totalCount}
        starredRepositories {totalCount}
        status {
            createdAt
            emoji
            emojiHTML
            expiresAt
            id
            indicatesLimitedAvailability
            message
            # organization {}
            updatedAt
            # user {}
        }
        # suggestedListNames {}
        # topRepositories(...) {totalCount pageInfo {} edges {} nodes {}}
        totalSponsorshipAmountAsSponsorInCents
        twitterUsername
        updatedAt
        url
        userViewType
        # viewerCanChangePinnedItems
        # viewerCanCreateProjects  # DEPRECATED
        # viewerCanFollow
        # viewerCanSponsor
        # viewerCopilotAgentCreatesChannel
        # viewerCopilotAgentLogUpdatesChannel
        # viewerCopilotAgentUpdatesChannel
        # viewerIsFollowing
        # viewerIsSponsoring
        watching {totalCount}
        websiteUrl
    }
    rateLimit {
        limit
        cost
        remaining
        resetAt
    }
}
