query($user: String!, $page_size: Int!, $cursor: String) {
    user(login: $user) {
        id
        login
        repositories(first: $page_size, after: $cursor) {
            totalCount
            pageInfo {
                endCursor
                startCursor
                hasPreviousPage
                hasNextPage
            }
            nodes {
                archivedAt
                autoMergeAllowed
                createdAt
                databaseId
                deleteBranchOnMerge
                description
                diskUsage
                forkCount
                forkingAllowed
                hasDiscussionsEnabled
                hasIssuesEnabled
                hasProjectsEnabled
                hasSponsorshipsEnabled
                hasVulnerabilityAlertsEnabled
                hasWikiEnabled
                homepageUrl
                id
                isArchived
                isBlankIssuesEnabled
                isDisabled
                isEmpty
                isFork
                isInOrganization
                isLocked
                isMirror
                isPrivate
                isSecurityPolicyEnabled
                isTemplate
                isUserConfigurationRepository
                latestRelease {id name publishedAt tagName url}
                licenseInfo {id key name nickname description body url}
                lockReason
                mergeCommitAllowed
                mergeCommitMessage
                mergeCommitTitle
                name
                nameWithOwner
                openGraphImageUrl
                owner {login}
                planFeatures {
                    codeowners
                    draftPullRequests
                    maximumAssignees
                    maximumManualReviewRequests
                    teamReviewRequests
                }
                primaryLanguage {color id name}
                pushedAt
                rebaseMergeAllowed
                resourcePath
                squashMergeAllowed
                squashMergeCommitMessage
                squashMergeCommitTitle
                stargazerCount
                updatedAt
                url
                usesCustomOpenGraphImage
                visibility
                webCommitSignoffRequired
            }
        }
    }
    rateLimit {
        limit
        cost
        remaining
        resetAt
    }
}
