model (
    name warehouse.raw.github__user,
    kind full,
    grain (user_id),
    tags (github),
);


select
    user__id as user_id,

    user__bio,
    user__bio_html,
    user__commit_comments__total_count,
    user__company,
    user__company_html,
    user__created_at,
    user__database_id,
    user__email,
    user__enterprises__total_count,
    user__estimated_next_sponsors_payout_in_cents,
    user__followers__total_count,
    user__following__total_count,
    user__gist_comments__total_count,
    user__gists__total_count,
    user__has_sponsors_listing,
    user__interaction_ability__limit,
    user__interaction_ability__origin,
    user__is_bounty_hunter,
    user__is_campus_expert,
    user__is_developer_program_member,
    user__is_employee,
    user__is_git_hub_star,
    user__is_hireable,
    user__is_site_admin,
    user__issue_comments__total_count,
    user__issues__total_count,
    user__item_showcase__has_pinned_items,
    user__item_showcase__items__total_count,
    user__lifetime_received_sponsorship_values__total_count,
    user__lists__total_count,
    user__login,
    user__monthly_estimated_sponsors_income_in_cents,
    user__name,
    user__organizations__total_count,
    user__packages__total_count,
    user__pinnable_items__total_count,
    user__pinned_items__total_count,
    user__pinned_items_remaining,
    user__projects_resource_path,
    user__projects_url,
    user__projects_v2__total_count,
    user__pronouns,
    user__public_keys__total_count,
    user__pull_requests__total_count,
    user__recent_projects__total_count,
    user__repositories__total_count,
    user__repositories_contributed_to__total_count,
    user__repository_discussion_comments__total_count,
    user__repository_discussions__total_count,
    user__resource_path,
    user__saved_replies__total_count,
    user__social_accounts__total_count,
    user__sponsoring__total_count,
    user__sponsors__total_count,
    user__sponsors_activities__total_count,
    user__sponsorship_newsletters__total_count,
    user__sponsorships_as_maintainer__total_count,
    user__sponsorships_as_sponsor__total_count,
    user__starred_repositories__total_count,
    user__status__created_at,
    user__status__emoji,
    user__status__emoji_html,
    user__status__id,
    user__status__indicates_limited_availability,
    user__status__message,
    user__status__updated_at,
    user__total_sponsorship_amount_as_sponsor_in_cents,
    user__updated_at,
    user__url,
    user__user_view_type,
    user__watching__total_count,
    user__website_url,

    _dlt_id,
    _dlt_load_id,
    make_timestamp(1000000 * _dlt_load_id::bigint) as _load_ts,
from landing.github_user.user
;
