model (
    name warehouse.raw_github.user,
    kind full,
    grain (user_id),
    tags (github),
    allow_partials true,
    audits (
        not_null(columns=[
            user_id,
            _dlt_id,
            _dlt_load_id,
            _load_ts,
        ]),
        unique_values(columns=[
            user_id,
            _dlt_id,
        ]),
    ),
);


select
    user__id as user_id,

    user__bio as bio,
    user__bio_html as bio_html,
    user__commit_comments__total_count as commit_comments_total_count,
    user__company as company,
    user__company_html as company_html,
    user__created_at as created_at,
    user__database_id as database_id,
    user__email as email,
    user__enterprises__total_count as enterprises_total_count,
    user__estimated_next_sponsors_payout_in_cents as estimated_next_sponsors_payout_in_cents,
    user__followers__total_count as followers_total_count,
    user__following__total_count as following_total_count,
    user__gist_comments__total_count as gist_comments_total_count,
    user__gists__total_count as gists_total_count,
    user__has_sponsors_listing as has_sponsors_listing,
    user__interaction_ability__limit as interaction_ability_limit,
    user__interaction_ability__origin as interaction_ability_origin,
    user__is_bounty_hunter as is_bounty_hunter,
    user__is_campus_expert as is_campus_expert,
    user__is_developer_program_member as is_developer_program_member,
    user__is_employee as is_employee,
    user__is_git_hub_star as is_git_hub_star,
    user__is_hireable as is_hireable,
    user__is_site_admin as is_site_admin,
    user__issue_comments__total_count as issue_comments_total_count,
    user__issues__total_count as issues_total_count,
    user__item_showcase__has_pinned_items as item_showcase_has_pinned_items,
    user__item_showcase__items__total_count as item_showcase_items_total_count,
    user__lifetime_received_sponsorship_values__total_count as lifetime_received_sponsorship_values_total_count,
    user__lists__total_count as lists_total_count,
    user__login as login,
    user__monthly_estimated_sponsors_income_in_cents as monthly_estimated_sponsors_income_in_cents,
    user__name as name,
    user__organizations__total_count as organizations_total_count,
    user__packages__total_count as packages_total_count,
    user__pinnable_items__total_count as pinnable_items_total_count,
    user__pinned_items__total_count as pinned_items_total_count,
    user__pinned_items_remaining as pinned_items_remaining,
    user__projects_resource_path as projects_resource_path,
    user__projects_url as projects_url,
    user__projects_v2__total_count as projects_v2_total_count,
    user__pronouns as pronouns,
    user__public_keys__total_count as public_keys_total_count,
    user__pull_requests__total_count as pull_requests_total_count,
    user__recent_projects__total_count as recent_projects_total_count,
    user__repositories__total_count as repositories_total_count,
    user__repositories_contributed_to__total_count as repositories_contributed_to_total_count,
    user__repository_discussion_comments__total_count as repository_discussion_comments_total_count,
    user__repository_discussions__total_count as repository_discussions_total_count,
    user__resource_path as resource_path,
    user__saved_replies__total_count as saved_replies_total_count,
    user__social_accounts__total_count as social_accounts_total_count,
    user__sponsoring__total_count as sponsoring_total_count,
    user__sponsors__total_count as sponsors_total_count,
    user__sponsors_activities__total_count as sponsors_activities_total_count,
    user__sponsorship_newsletters__total_count as sponsorship_newsletters_total_count,
    user__sponsorships_as_maintainer__total_count as sponsorships_as_maintainer_total_count,
    user__sponsorships_as_sponsor__total_count as sponsorships_as_sponsor_total_count,
    user__starred_repositories__total_count as starred_repositories_total_count,
    user__status__created_at as status_created_at,
    user__status__emoji as status_emoji,
    user__status__emoji_html as status_emoji_html,
    user__status__id as status_id,
    user__status__indicates_limited_availability as status_indicates_limited_availability,
    user__status__message as status_message,
    user__status__updated_at as status_updated_at,
    user__total_sponsorship_amount_as_sponsor_in_cents as total_sponsorship_amount_as_sponsor_in_cents,
    user__updated_at as updated_at,
    user__url as url,
    user__user_view_type as user_view_type,
    user__watching__total_count as watching_total_count,
    user__website_url as website_url,

    _dlt_id,
    _dlt_load_id,
    make_timestamp(1000000 * _dlt_load_id::bigint) as _load_ts,
from landing.github_user.user
;
