model (
    name warehouse.raw_oura.sleep,
    kind full,
    grain (id),
    tags (oura),
    columns (
        id varchar,
        bedtime_start timestamptz,
        bedtime_end timestamptz,

        day date,
        average_breath decimal(6, 3),
        average_heartrate decimal(6, 3),
        average_hrv integer,
        awake_time integer,
        deep_sleep_duration integer,
        efficiency integer,
        latency integer,
        light_sleep_duration integer,
        low_battery_alert boolean,
        lowest_heartrate integer,
        period integer,
        readiness_score_delta integer,
        rem_sleep_duration integer,
        restless_periods integer,
        sleep_algorithm_version varchar,
        sleep_score_delta integer,
        time_in_bed integer,
        total_sleep_duration integer,
        type varchar,
        sleep_analysis_reason varchar,

        movement_30_sec varchar,
        sleep_phase_30_sec varchar,
        sleep_phase_5_min varchar,
        app_sleep_phase_5_min varchar,

        heartrate__interval decimal(6, 2),
        heartrate__items decimal(6, 2)[],
        heartrate__timestamp timestamptz,
        hrv__interval decimal(6, 2),
        hrv__items decimal(6, 2)[],
        hrv__timestamp timestamptz,
        readiness__score decimal(6, 2),
        readiness__temperature_deviation decimal(6, 2),
        readiness__temperature_trend_deviation decimal(6, 2),
        readiness__contributors__activity_balance integer,
        readiness__contributors__body_temperature integer,
        readiness__contributors__hrv_balance integer,
        readiness__contributors__previous_day_activity integer,
        readiness__contributors__previous_night integer,
        readiness__contributors__recovery_index integer,
        readiness__contributors__resting_heartrate integer,
        readiness__contributors__sleep_balance integer,

        _dlt_id varchar,
        _dlt_load_id varchar,
        _load_ts timestamp,
    ),
    audits (
        not_null(columns=[
            id,
            bedtime_start,
            bedtime_end,
            day,
            _dlt_id,
            _dlt_load_id,
            _load_ts,
        ]),
        unique_values(columns=[
            id,
            _dlt_id,
        ]),
    ),
);


select
    id,
    bedtime_start,
    bedtime_end,

    "day",
    average_breath,
    average_heart_rate as average_heartrate,
    average_hrv,
    awake_time,
    deep_sleep_duration,
    efficiency,
    latency,
    light_sleep_duration,
    low_battery_alert,
    lowest_heart_rate as lowest_heartrate,
    period,
    readiness_score_delta,
    rem_sleep_duration,
    restless_periods,
    sleep_algorithm_version,
    sleep_score_delta,
    time_in_bed,
    total_sleep_duration,
    type,
    sleep_analysis_reason,

    movement_30_sec,
    sleep_phase_30_sec,
    sleep_phase_5_min,
    app_sleep_phase_5_min,

    -- heartrate,
    heart_rate->>'$.interval' as heartrate__interval,
    heart_rate->>'$.items' as heartrate__items,
    heart_rate->>'$.timestamp' as heartrate__timestamp,

    -- hrv,
    hrv->>'$.interval' as hrv__interval,
    hrv->>'$.items' as hrv__items,
    hrv->>'$.timestamp' as hrv__timestamp,

    -- readiness,
    readiness->>'$.score' as readiness__score,
    readiness->>'$.temperature_deviation' as readiness__temperature_deviation,
    readiness->>'$.temperature_trend_deviation' as readiness__temperature_trend_deviation,
    readiness->>'$.contributors.activity_balance' as readiness__contributors__activity_balance,
    readiness->>'$.contributors.body_temperature' as readiness__contributors__body_temperature,
    readiness->>'$.contributors.hrv_balance' as readiness__contributors__hrv_balance,
    readiness->>'$.contributors.previous_day_activity' as readiness__contributors__previous_day_activity,
    readiness->>'$.contributors.previous_night' as readiness__contributors__previous_night,
    readiness->>'$.contributors.recovery_index' as readiness__contributors__recovery_index,
    readiness->>'$.contributors.resting_heart_rate' as readiness__contributors__resting_heartrate,
    readiness->>'$.contributors.sleep_balance' as readiness__contributors__sleep_balance,

    _dlt_id,
    _dlt_load_id,
    @dlt_load_ts(_dlt_load_id) as _load_ts,
from landing.oura.sleep
;
