model (
    name warehouse.coding.github_user,
    kind full,
    grain (user_id),
    tags (github),
    audits (
        not_null(columns=[
            user_id,
            _load_ts,
        ]),
        unique_values(columns=[
            user_id,
        ]),
    ),
);


select
    user_id,

    bio,
    bio_html,
    commit_comments_total_count,
    company,
    company_html,
    created_at,
    database_id,
    email,
    enterprises_total_count,
    estimated_next_sponsors_payout_in_cents,
    followers_total_count,
    following_total_count,
    gist_comments_total_count,
    gists_total_count,
    has_sponsors_listing,
    interaction_ability_limit,
    interaction_ability_origin,
    is_bounty_hunter,
    is_campus_expert,
    is_developer_program_member,
    is_employee,
    is_git_hub_star,
    is_hireable,
    is_site_admin,
    issue_comments_total_count,
    issues_total_count,
    item_showcase_has_pinned_items,
    item_showcase_items_total_count,
    lifetime_received_sponsorship_values_total_count,
    lists_total_count,
    login as username,
    monthly_estimated_sponsors_income_in_cents,
    name,
    organizations_total_count,
    packages_total_count,
    pinnable_items_total_count,
    pinned_items_total_count,
    pinned_items_remaining,
    projects_resource_path,
    projects_url,
    projects_v2_total_count,
    pronouns,
    public_keys_total_count,
    pull_requests_total_count,
    recent_projects_total_count,
    repositories_total_count,
    repositories_contributed_to_total_count,
    repository_discussion_comments_total_count,
    repository_discussions_total_count,
    resource_path,
    saved_replies_total_count,
    social_accounts_total_count,
    sponsoring_total_count,
    sponsors_total_count,
    sponsors_activities_total_count,
    sponsorship_newsletters_total_count,
    sponsorships_as_maintainer_total_count,
    sponsorships_as_sponsor_total_count,
    starred_repositories_total_count,
    status_created_at,
    status_emoji,
    status_emoji_html,
    status_id,
    status_indicates_limited_availability,
    status_message,
    status_updated_at,
    total_sponsorship_amount_as_sponsor_in_cents,
    updated_at,
    url,
    user_view_type,
    watching_total_count,
    website_url,

    _load_ts,
from warehouse.raw_github.user
qualify _dlt_load_id = max(_dlt_load_id) over ()
;
